function pglyoxalbcnt(varargin);
% pglyoxalbcnt( [...] );
% B Ctr N Trigger
h = timeplot({'BCtr_NTrigger'}, ...
      'B Ctr N Trigger', ...
      'N Trigger', ...
      {'BCtr\_NTrigger'}, ...
      varargin{:} );
